# Generated by Django 4.2.7 on 2023-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='data_received',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='data_sent',
            field=models.FloatField(default=0),
        ),
    ]
